#'GetDiscriptionCSV
#'@description
#'Get a short Discription from all Cores and save them as csv.
#'@param data List of data generates by the MultiExcelLoader function.
#'@param saveAsCSV Bool indicating if the data should be exported a CSV in the used working directory.
#'@import compositions readxl
#'@importFrom utils read.csv read.table write.table
#'@export
#'@return Save CSV in workspace.
#'@author Tim Kroeger
#'@note This function has only been developed for the Alfred Wegener Institute Helmholtz Centre for Polar and Marine Research and should therefore only be used in combination with their database.

GetDiscriptionCSV = function(data, saveAsCSV = FALSE){

  if(!is.null(data[["Description"]])){

    OutPutDiscriptionMatrix = matrix(NA, nrow = dim(data[["Description"]][[1]])[1],ncol = length(ls(data[["Description"]])))

    for(i in 1:length(ls(data[["Description"]]))){

      TempData = data[["Description"]][[i]]

      OutPutDiscriptionMatrix[,i]=TempData[,2]

    }

    row.names(OutPutDiscriptionMatrix)=data[["Description"]][[1]][,1]

    if(saveAsCSV){

      write.table(OutPutDiscriptionMatrix,file = paste(getwd(),"/","Description",".csv",sep=""),
                  append = FALSE,na = "", sep = "; ", row.names = T, col.names = F,quote = F)

    }

    invisible(OutPutDiscriptionMatrix)

  }else{

    stop("No Description Files found! Data must be generated by MultiExcelLoader")

  }
}
