#'SaveOutput
#'@description
#'Save all Outputs from the data generated by MultiExcelLoader and Multivar as a CSV.
#'@param data List of data generates by the MultiExcelLoader oder Multivar function.
#'@import compositions readxl
#'@importFrom utils read.csv read.table write.table
#'@export
#'@return Save CSV in Output Folder.
#'@author Tim Kroeger
#'@note This function has only been developed for the Alfred Wegener Institute Helmholtz Centre for Polar and Marine Research and should therefore only be used in combination with their database.

SaveOutput = function(data){

  orginalWorkingDirectoryPath=getwd()

  getwdTry <-  try(setwd(paste(getwd(),.Platform[2],paste("Out_",data$Filter,sep = ""),sep="")),silent = TRUE)

  if(class(getwdTry) == "try-error"){

    dir.create(paste(getwd(),.Platform[2],paste("Out_",data$Filter,sep = ""),sep=""))

    setwd(paste(getwd(),.Platform[2],paste("Out_",data$Filter,sep = ""),sep=""))

  }

  #Discription File

  if(!is.null(data[["Description"]])){

    OutPutDiscriptionMatrix = matrix(NA, nrow = dim(data[["Description"]][[1]])[1],ncol = length(ls(data[["Description"]])))

    for(i in 1:length(ls(data[["Description"]]))){

      TempData = data[["Description"]][[i]]

      OutPutDiscriptionMatrix[,i]=TempData[,2]

    }

    row.names(OutPutDiscriptionMatrix)=data[["Description"]][[1]][,1]

    turnedOutPutDiscriptionMatrix=OutPutDiscriptionMatrix

      write.table(turnedOutPutDiscriptionMatrix,file = paste(getwd(),"/","Metadata",".csv",sep=""),
                  append = FALSE,na = "", sep = ";", row.names = T, col.names = F,quote = F)

  }

  #GiveOutDiatomMetadata

  counter = 0

  DiatomturnedOutPutDiscriptionMatrix = turnedOutPutDiscriptionMatrix

  while(counter < dim(DiatomturnedOutPutDiscriptionMatrix)[2]){

    counter = counter+1

    if(!as.logical(DiatomturnedOutPutDiscriptionMatrix[which(row.names(DiatomturnedOutPutDiscriptionMatrix)=="DiatomDataNotFilterd"),counter])){

      DiatomturnedOutPutDiscriptionMatrix = DiatomturnedOutPutDiscriptionMatrix[,-counter]

      counter = counter-1

    }
  }
  write.table(DiatomturnedOutPutDiscriptionMatrix,file = paste(getwd(),"/","Metadata_Only_Diatom",".csv",sep=""),
              append = FALSE,na = "", sep = ";", row.names = T, col.names = F,quote = F)

  #GiveOutCarbonMetadata

  counter = 0

  CarbonturnedOutPutDiscriptionMatrix = turnedOutPutDiscriptionMatrix

  while(counter < dim(CarbonturnedOutPutDiscriptionMatrix)[2]){

    counter = counter+1

    if(!as.logical(CarbonturnedOutPutDiscriptionMatrix[which(row.names(CarbonturnedOutPutDiscriptionMatrix)=="CarbonDataNotFilterd"),counter])){

      CarbonturnedOutPutDiscriptionMatrix = CarbonturnedOutPutDiscriptionMatrix[,-counter]

      counter = counter-1

    }
  }
  write.table(CarbonturnedOutPutDiscriptionMatrix,file = paste(getwd(),"/","Metadata_Only_Carbon",".csv",sep=""),
              append = FALSE,na = "", sep = ";", row.names = T, col.names = F,quote = F)

  #Filterlist

  write.table(data$FilterList,file = paste(getwd(),"/","Filter",".txt",sep=""),
              append = FALSE,na = "", sep = "\t", row.names = F, col.names = F,quote = F)


  #Save MetaData on Sever when possible

  MacPath = "/Volumes/projects/p_arclakes"
  PathMetadata = "/ArcLakesDB/COREDATA/METADATA/"

  directory = NULL

  if(is.null(directory)){

    for (PossibleDirectory in letters){

      getwdTry <-  try(setwd(paste(toupper(PossibleDirectory),":",PathMetadata,sep="")),
                       silent = TRUE)

      if(!class(getwdTry) == "try-error"){

        directory = paste(toupper(PossibleDirectory),":",sep = "")

      }
    }
  }

  if(is.null(directory)){

    getwdTry <-  try(setwd(MacPath),
                     silent = TRUE)

    if(!class(getwdTry) == "try-error"){

      directory = MacPath

    }
  }

  if(is.null(directory)){

    setwd(orginalWorkingDirectoryPath)

  }

  if(!is.null(directory)){

  setwd(paste(directory,PathMetadata,sep=""))

  write.table(turnedOutPutDiscriptionMatrix,file = paste(getwd(),"/","Metadata",".csv",sep=""),
              append = FALSE,na = "", sep = "; ", row.names = T, col.names = F,quote = F)

  cat("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
      "Metadata Uploaded",sep="")

  }

  setwd(orginalWorkingDirectoryPath)

}
























